CREATE DATABASE BANK;
USE BANK;
CREATE TABLE CLIENTE(
	ID_CLIENTE INT(10) AUTO_INCREMENT PRIMARY KEY,
    NAME_CLIENTE VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE KEY
);
CREATE TABLE CONTA_BANCARIA(
    NUMERO_CONTA INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	TIPO_CONTA VARCHAR(1) NOT NULL,
    SALDO DOUBLE(10,2) NOT NULL, 
    CHEQUE_ESPECIAL DOUBLE(10,2),
    CPF_CLIENTE VARCHAR(11), 
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF)
);
CREATE TABLE EXTRATO(
	ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DATA_ACAO DATE,
    DESCRICAO VARCHAR(255),
    TIPO_CONTA VARCHAR(15),
    CPF_CLIENTE VARCHAR(15),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF)
);
